strictPeerDependencies: false
sideEffectsCache: false
linkWorkspacePackages: true

packages:
  - packages/*
  - examples/*
  - ci

allowBuilds:
  "@nestjs/core": true
  "@swc/core": true
  esbuild: true
  puppeteer: true
  unrs-resolver: true
