strictPeerDependencies: false
sideEffectsCache: false
linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - "@cyco130/eslint-config"
  - "kill-em-all"

packages:
  - packages/*
  - examples/*
  - ci

allowBuilds:
  "@nestjs/core": true
  "@swc/core": true
  esbuild: true
  puppeteer: true
  unrs-resolver: true
